# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://iamstevenliu.com
title: Steven's Personal Website
email: rendong_liu@hotmaul.com
description: > # "Hi, This is a personal Blog belong to Rendong Liu. You can also call me Steven"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: 
  - title: github
    url: 
  - title: linkedin
    url: 
